In [1]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [2]:
tf.__version__

'2.10.0'

In [3]:
import os

In [4]:
rootdir = './data/'
labels = []

for file in os.listdir(rootdir):
    labels.append(file)
    

In [5]:
labels

['1', '100519733006', '100519733015']

In [6]:
x, y = [] , []


In [7]:
from PIL import Image

In [8]:
for index , label in enumerate(labels):
    path = rootdir+ label
    for file in os.listdir(path):
        image = Image.open(os.path.join( path, file) , "r")
        image = np.asarray(image)
        x.append(image / 255)
        y.append(index)

In [9]:
len(x)

603

In [10]:
x = np.asarray(x)
y = np.asarray(y)

In [11]:
len(y)

603

In [12]:
type(x[6])

numpy.ndarray

In [13]:
x[0]

array([[0.58039216, 0.58039216, 0.58431373, ..., 0.63921569, 0.63921569,
        0.63921569],
       [0.57647059, 0.57647059, 0.57647059, ..., 0.63921569, 0.63921569,
        0.63921569],
       [0.57647059, 0.57647059, 0.57647059, ..., 0.64313725, 0.63921569,
        0.63529412],
       ...,
       [0.37254902, 0.56470588, 0.6745098 , ..., 0.27058824, 0.26666667,
        0.2627451 ],
       [0.33333333, 0.49411765, 0.61568627, ..., 0.2627451 , 0.25882353,
        0.25882353],
       [0.32941176, 0.45098039, 0.56078431, ..., 0.25490196, 0.25882353,
        0.2627451 ]])

In [14]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=[256, 256]),
    tf.keras.layers.Dense(200, activation="relu"),
    tf.keras.layers.Dense(150, activation="relu"),
    tf.keras.layers.Dense(len(labels), activation="softmax")
])

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 65536)             0         
                                                                 
 dense (Dense)               (None, 200)               13107400  
                                                                 
 dense_1 (Dense)             (None, 150)               30150     
                                                                 
 dense_2 (Dense)             (None, 3)                 453       
                                                                 
Total params: 13,138,003
Trainable params: 13,138,003
Non-trainable params: 0
_________________________________________________________________


In [16]:
model.layers

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
xtrain , xtest , ytrain , ytest = train_test_split(x , y, test_size = 0.2)

In [19]:
len(xtrain)

482

In [20]:
model.compile(loss = "sparse_categorical_crossentropy", optimizer = "adam" , metrics = ["accuracy"])

In [21]:
xtrain , xvalid = xtrain[:140], xtrain[140:]
ytrain , yvalid = ytrain[:140] , ytrain[140:]

In [22]:
len(xtrain)

140

In [27]:
checkpoint_cb = tf.keras.callbacks.ModelCheckpoint('model1ANN.h5' , save_best_only = True)
early_stopping_cb = tf.keras.callbacks.EarlyStopping(patience=4,restore_best_weights=True)


In [28]:
xtrain = np.asarray(xtrain)

In [29]:
xtrain.shape

(140, 256, 256)

In [30]:
history = model.fit(xtrain ,ytrain , epochs = 30,validation_data = (xvalid, yvalid) ,
                    callbacks = [checkpoint_cb , early_stopping_cb])

Epoch 1/30
5/5 [==============================] - 1s 340ms/step - loss: 6.1477e-07 - accuracy: 1.0000 - val_loss: 5.7386e-06 - val_accuracy: 1.0000
Epoch 2/30
5/5 [==============================] - 2s 324ms/step - loss: 6.0966e-07 - accuracy: 1.0000 - val_loss: 5.6905e-06 - val_accuracy: 1.0000
Epoch 3/30
5/5 [==============================] - 1s 273ms/step - loss: 6.0626e-07 - accuracy: 1.0000 - val_loss: 5.6428e-06 - val_accuracy: 1.0000
Epoch 4/30
5/5 [==============================] - 1s 273ms/step - loss: 6.0115e-07 - accuracy: 1.0000 - val_loss: 5.5971e-06 - val_accuracy: 1.0000
Epoch 5/30
5/5 [==============================] - 1s 295ms/step - loss: 5.9604e-07 - accuracy: 1.0000 - val_loss: 5.5515e-06 - val_accuracy: 1.0000
Epoch 6/30
5/5 [==============================] - 1s 283ms/step - loss: 5.9263e-07 - accuracy: 1.0000 - val_loss: 5.5034e-06 - val_accuracy: 1.0000
Epoch 7/30
5/5 [==============================] - 1s 290ms/step - loss: 5.8838e-07 - accuracy: 1.0000 - val_loss

In [31]:
preds = model.predict(xtest)

4/4 [==============================] - 0s 20ms/step


In [32]:
preds

array([[5.21327495e-11, 7.36590550e-07, 9.99999285e-01],
       [1.00000000e+00, 1.47107398e-25, 3.57074873e-12],
       [9.10934887e-07, 2.01038059e-17, 9.99999046e-01],
       [1.45119819e-10, 1.40292723e-32, 1.00000000e+00],
       [7.86673329e-34, 1.00000000e+00, 2.15266444e-34],
       [5.60049099e-12, 2.86185165e-13, 1.00000000e+00],
       [2.96197681e-16, 1.00000000e+00, 4.44484624e-22],
       [8.51660119e-15, 2.15390790e-31, 1.00000000e+00],
       [1.47932031e-22, 1.00000000e+00, 5.77075270e-25],
       [5.22676371e-17, 1.00000000e+00, 1.62440727e-20],
       [1.00000000e+00, 1.77099511e-21, 1.11085696e-10],
       [1.12494630e-18, 1.00000000e+00, 4.56953380e-26],
       [3.82728211e-16, 1.00000000e+00, 8.02527611e-22],
       [1.00000000e+00, 1.46454331e-20, 2.60471875e-08],
       [8.31744612e-14, 1.33417011e-33, 1.00000000e+00],
       [1.39530856e-13, 1.96808881e-30, 1.00000000e+00],
       [6.80199684e-17, 1.00000000e+00, 1.51275590e-22],
       [1.00000000e+00, 7.41319

In [33]:
x = []
for pred in preds:
    x.append(np.argmax(pred))

In [34]:
ytest

array([2, 0, 2, 2, 1, 2, 1, 2, 1, 1, 0, 1, 1, 0, 2, 2, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 1, 0, 0, 2, 2, 0, 0, 2, 1, 1,
       1, 2, 0, 2, 2, 1, 0, 0, 1, 2, 2, 0, 2, 0, 2, 2, 1, 0, 1, 2, 2, 2,
       2, 2, 2, 1, 1, 0, 0, 1, 2, 1, 2, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 2,
       1, 1, 0, 2, 0, 0, 0, 0, 0, 1, 1, 1, 2, 0, 0, 0, 2, 1, 0, 1, 1, 1,
       2, 0, 0, 1, 1, 1, 2, 0, 1, 2, 2])

In [35]:
from sklearn.metrics import confusion_matrix

In [36]:
confusion_matrix(ytest, x)

array([[37,  0,  0],
       [ 0, 43,  0],
       [ 0,  0, 41]], dtype=int64)