In [4]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [5]:
tf.__version__

'2.10.0'

In [6]:
import os

In [7]:
rootdir = './data/'
labels = []

for file in os.listdir(rootdir):
    labels.append(file)
    

In [8]:
labels

['1', '100519733006', '100519733015', '2']

In [9]:
x, y = [] , []


In [10]:
from PIL import Image

In [11]:
for index , label in enumerate(labels):
    path = rootdir+ label
    for file in os.listdir(path):
        image = Image.open(os.path.join( path, file) , "r")
        image = np.asarray(image)
        x.append(image / 255)
        y.append(index)

In [12]:
len(x)

643

In [13]:
x = np.asarray(x)
y = np.asarray(y)

In [14]:
len(y)

643

In [15]:
type(x[6])

numpy.ndarray

In [16]:
x[0]

array([[0.58039216, 0.58039216, 0.58431373, ..., 0.63921569, 0.63921569,
        0.63921569],
       [0.57647059, 0.57647059, 0.57647059, ..., 0.63921569, 0.63921569,
        0.63921569],
       [0.57647059, 0.57647059, 0.57647059, ..., 0.64313725, 0.63921569,
        0.63529412],
       ...,
       [0.37254902, 0.56470588, 0.6745098 , ..., 0.27058824, 0.26666667,
        0.2627451 ],
       [0.33333333, 0.49411765, 0.61568627, ..., 0.2627451 , 0.25882353,
        0.25882353],
       [0.32941176, 0.45098039, 0.56078431, ..., 0.25490196, 0.25882353,
        0.2627451 ]])

In [17]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=[256, 256]),
    tf.keras.layers.Dense(200, activation="relu"),
    tf.keras.layers.Dense(150, activation="relu"),
    tf.keras.layers.Dense(len(labels), activation="softmax")
])

In [18]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 65536)             0         
                                                                 
 dense (Dense)               (None, 200)               13107400  
                                                                 
 dense_1 (Dense)             (None, 150)               30150     
                                                                 
 dense_2 (Dense)             (None, 4)                 604       
                                                                 
Total params: 13,138,154
Trainable params: 13,138,154
Non-trainable params: 0
_________________________________________________________________


In [19]:
model.layers

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
xtrain , xtest , ytrain , ytest = train_test_split(x , y, test_size = 0.2)

In [22]:
len(xtrain)

514

In [23]:
model.compile(loss = "sparse_categorical_crossentropy", optimizer = "adam" , metrics = ["accuracy"])

In [24]:
xtrain , xvalid = xtrain[:140], xtrain[140:]
ytrain , yvalid = ytrain[:140] , ytrain[140:]

In [25]:
len(xtrain)

140

In [26]:
checkpoint_cb = tf.keras.callbacks.ModelCheckpoint('model1ANN.h5' , save_best_only = True)
early_stopping_cb = tf.keras.callbacks.EarlyStopping(patience=4,restore_best_weights=True)


In [27]:
xtrain = np.asarray(xtrain)

In [28]:
xtrain.shape

(140, 256, 256)

In [29]:
history = model.fit(xtrain ,ytrain , epochs = 30,validation_data = (xvalid, yvalid) ,
                    callbacks = [checkpoint_cb , early_stopping_cb])

Epoch 1/30
5/5 [==============================] - 4s 511ms/step - loss: 11.3344 - accuracy: 0.4000 - val_loss: 4.8615 - val_accuracy: 0.3503
Epoch 2/30
5/5 [==============================] - 2s 383ms/step - loss: 1.6491 - accuracy: 0.7143 - val_loss: 1.0999 - val_accuracy: 0.8663
Epoch 3/30
5/5 [==============================] - 1s 350ms/step - loss: 0.5524 - accuracy: 0.9429 - val_loss: 0.3061 - val_accuracy: 0.9572
Epoch 4/30
5/5 [==============================] - 2s 377ms/step - loss: 0.2574 - accuracy: 0.9786 - val_loss: 0.0818 - val_accuracy: 0.9920
Epoch 5/30
5/5 [==============================] - 1s 153ms/step - loss: 0.0011 - accuracy: 1.0000 - val_loss: 0.1084 - val_accuracy: 0.9920
Epoch 6/30
5/5 [==============================] - 1s 161ms/step - loss: 9.0338e-04 - accuracy: 1.0000 - val_loss: 0.1232 - val_accuracy: 0.9840
Epoch 7/30
5/5 [==============================] - 1s 166ms/step - loss: 0.0033 - accuracy: 1.0000 - val_loss: 0.0893 - val_accuracy: 0.9893
Epoch 8/30
5/5 

In [30]:
preds = model.predict(xtest)

5/5 [==============================] - 0s 20ms/step


In [31]:
preds

array([[1.00000000e+00, 9.79039939e-12, 3.26639721e-33, 1.00117661e-13],
       [5.84508371e-06, 3.30987918e-17, 9.99994159e-01, 7.69817023e-12],
       [1.89117000e-01, 2.76124826e-13, 7.55409637e-05, 8.10807407e-01],
       [2.88596441e-32, 1.00000000e+00, 8.40113116e-19, 8.70770706e-28],
       [3.12212999e-15, 5.70442924e-27, 1.00000000e+00, 2.94660329e-17],
       [3.39288097e-23, 1.00000000e+00, 0.00000000e+00, 2.14773087e-30],
       [1.00000000e+00, 5.67878817e-12, 4.99284212e-38, 5.24968871e-15],
       [1.00000000e+00, 1.23442090e-11, 2.98617824e-37, 8.11720567e-16],
       [1.00000000e+00, 7.12530035e-11, 0.00000000e+00, 1.86563941e-15],
       [1.23680317e-19, 1.00000000e+00, 0.00000000e+00, 3.66212806e-26],
       [5.63828455e-15, 7.69769380e-14, 1.00000000e+00, 3.16423917e-15],
       [7.60150520e-09, 1.00000000e+00, 6.12902577e-19, 2.30859571e-15],
       [1.00000000e+00, 4.30001998e-12, 1.96070085e-37, 1.58057153e-15],
       [7.10150702e-17, 9.25068509e-29, 1.00000000e

In [32]:
x = []
for pred in preds:
    x.append(np.argmax(pred))

In [33]:
ytest

array([0, 2, 3, 1, 2, 1, 0, 0, 0, 1, 2, 1, 0, 2, 0, 1, 1, 1, 3, 1, 1, 2,
       2, 0, 0, 2, 1, 2, 1, 0, 2, 0, 0, 3, 1, 3, 1, 0, 0, 1, 1, 0, 2, 1,
       2, 0, 1, 0, 1, 0, 2, 1, 0, 3, 2, 0, 1, 0, 2, 2, 2, 2, 1, 1, 2, 1,
       0, 1, 2, 0, 1, 2, 3, 2, 0, 2, 2, 1, 1, 1, 0, 2, 0, 0, 2, 2, 2, 2,
       3, 1, 0, 0, 1, 0, 2, 1, 0, 0, 1, 2, 2, 1, 0, 0, 2, 0, 1, 2, 1, 1,
       0, 2, 2, 3, 0, 1, 1, 2, 2, 0, 1, 0, 2, 0, 0, 1, 1, 1, 1])

In [34]:
from sklearn.metrics import confusion_matrix

In [35]:
confusion_matrix(ytest, x)

array([[39,  1,  0,  0],
       [ 0, 43,  0,  0],
       [ 0,  0, 38,  0],
       [ 0,  0,  0,  8]], dtype=int64)