In [1]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [2]:
tf.__version__

'2.10.0'

In [6]:
import os

In [50]:
rootdir = './test/ANN/'
labels = []

for file in os.listdir(rootdir):
    labels.append(file)
    

In [51]:
labels

['100519733015']

In [52]:
x, y = [] , []


In [53]:
from PIL import Image

In [54]:
for index , label in enumerate(labels):
    path = rootdir+ label
    for file in os.listdir(path):
        image = Image.open(os.path.join( path, file) , "r")
        image = np.asarray(image)
        x.append(image / 255)
        y.append(index)

In [55]:
len(x)

11

In [56]:
x = np.asarray(x)
y = np.asarray(y)

In [49]:
len(y)

11

In [20]:
type(x[6])

numpy.ndarray

In [21]:
x[0]

array([[0.74901961, 0.74509804, 0.7372549 , ..., 0.11372549, 0.11372549,
        0.11372549],
       [0.74117647, 0.74117647, 0.7372549 , ..., 0.11372549, 0.11372549,
        0.11372549],
       [0.74117647, 0.7372549 , 0.7372549 , ..., 0.11372549, 0.11372549,
        0.11372549],
       ...,
       [0.59215686, 0.59607843, 0.6       , ..., 0.12941176, 0.06666667,
        0.09019608],
       [0.58823529, 0.59607843, 0.6       , ..., 0.14117647, 0.0745098 ,
        0.09019608],
       [0.58823529, 0.59215686, 0.6       , ..., 0.15294118, 0.08235294,
        0.10196078]])

In [22]:
# model = tf.keras.models.Sequential([
#     tf.keras.layers.Flatten(input_shape=[256, 256]),
#     tf.keras.layers.Dense(200, activation="relu"),
#     tf.keras.layers.Dense(150, activation="relu"),
#     tf.keras.layers.Dense(len(labels), activation="softmax")
# ])

model = tf.keras.models.load_model("model1ANN.h5")

In [23]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 65536)             0         
                                                                 
 dense (Dense)               (None, 200)               13107400  
                                                                 
 dense_1 (Dense)             (None, 150)               30150     
                                                                 
 dense_2 (Dense)             (None, 4)                 604       
                                                                 
Total params: 13,138,154
Trainable params: 13,138,154
Non-trainable params: 0
_________________________________________________________________


In [24]:
model.layers

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
xtrain , xtest , ytrain , ytest = train_test_split(x , y, test_size = 0.2)

In [22]:
len(xtrain)

514

In [23]:
model.compile(loss = "sparse_categorical_crossentropy", optimizer = "adam" , metrics = ["accuracy"])

In [24]:
xtrain , xvalid = xtrain[:140], xtrain[140:]
ytrain , yvalid = ytrain[:140] , ytrain[140:]

In [25]:
len(xtrain)

140

In [26]:
checkpoint_cb = tf.keras.callbacks.ModelCheckpoint('model1ANN.h5' , save_best_only = True)
early_stopping_cb = tf.keras.callbacks.EarlyStopping(patience=4,restore_best_weights=True)


In [27]:
xtrain = np.asarray(xtrain)

In [28]:
xtrain.shape

(140, 256, 256)

In [29]:
history = model.fit(xtrain ,ytrain , epochs = 30,validation_data = (xvalid, yvalid) ,
                    callbacks = [checkpoint_cb , early_stopping_cb])

Epoch 1/30
5/5 [==============================] - 4s 511ms/step - loss: 11.3344 - accuracy: 0.4000 - val_loss: 4.8615 - val_accuracy: 0.3503
Epoch 2/30
5/5 [==============================] - 2s 383ms/step - loss: 1.6491 - accuracy: 0.7143 - val_loss: 1.0999 - val_accuracy: 0.8663
Epoch 3/30
5/5 [==============================] - 1s 350ms/step - loss: 0.5524 - accuracy: 0.9429 - val_loss: 0.3061 - val_accuracy: 0.9572
Epoch 4/30
5/5 [==============================] - 2s 377ms/step - loss: 0.2574 - accuracy: 0.9786 - val_loss: 0.0818 - val_accuracy: 0.9920
Epoch 5/30
5/5 [==============================] - 1s 153ms/step - loss: 0.0011 - accuracy: 1.0000 - val_loss: 0.1084 - val_accuracy: 0.9920
Epoch 6/30
5/5 [==============================] - 1s 161ms/step - loss: 9.0338e-04 - accuracy: 1.0000 - val_loss: 0.1232 - val_accuracy: 0.9840
Epoch 7/30
5/5 [==============================] - 1s 166ms/step - loss: 0.0033 - accuracy: 1.0000 - val_loss: 0.0893 - val_accuracy: 0.9893
Epoch 8/30
5/5 

In [25]:
preds = model.predict(x)

1/1 [==============================] - 1s 783ms/step


In [26]:
preds

array([[3.46665786e-11, 4.04016253e-17, 1.00000000e+00, 8.10688268e-13],
       [1.27036074e-07, 3.29354355e-13, 9.99999881e-01, 6.02679906e-09],
       [6.51756593e-10, 2.09556425e-14, 1.00000000e+00, 1.04289494e-10],
       [1.27036074e-07, 3.29354355e-13, 9.99999881e-01, 6.02679906e-09],
       [1.38431335e-06, 1.08722623e-12, 9.99998569e-01, 3.82587650e-08],
       [1.41843177e-08, 5.83264556e-13, 1.00000000e+00, 2.16171925e-09],
       [1.41843177e-08, 5.83264556e-13, 1.00000000e+00, 2.16171925e-09],
       [1.41843177e-08, 5.83264556e-13, 1.00000000e+00, 2.16171925e-09],
       [8.73775052e-10, 1.27696343e-13, 1.00000000e+00, 1.89892421e-10],
       [6.51756593e-10, 2.09556425e-14, 1.00000000e+00, 1.04289494e-10],
       [6.51756593e-10, 2.09556425e-14, 1.00000000e+00, 1.04289494e-10]],
      dtype=float32)

In [27]:
x = []
for pred in preds:
    x.append(np.argmax(pred))

In [29]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
from sklearn.metrics import confusion_matrix

In [32]:
confusion_matrix(y, x)

array([[ 0, 11],
       [ 0,  0]], dtype=int64)

In [33]:
x

[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]