In [1]:
import tensorflow as tf
from tensorflow import keras 
import numpy as np
from PIL import Image

In [2]:
tf.__version__

'2.10.0'

In [3]:
import os

In [4]:
rootdir = "./test/CNN/"
labels = []
for file in os.listdir(rootdir):
    labels.append(file)
    

In [5]:
labels

['1']

In [6]:
x , y = [] , []

In [7]:
for index , label in enumerate(labels):
    path = rootdir + label
    for file in os.listdir(path):
        img = Image.open(os.path.join(path , file) , "r")
        img = np.asarray(img)
        x.append(img / 255)
        y.append(index)

In [8]:
len(x)

11

In [9]:
x[0]

array([[[0.16862745, 0.16470588, 0.15686275],
        [0.16078431, 0.15686275, 0.14901961],
        [0.17254902, 0.17254902, 0.16470588],
        ...,
        [0.75686275, 0.7254902 , 0.71764706],
        [0.75294118, 0.72156863, 0.71372549],
        [0.74901961, 0.71764706, 0.70980392]],

       [[0.16470588, 0.16078431, 0.15294118],
        [0.15686275, 0.15294118, 0.14509804],
        [0.16862745, 0.16862745, 0.16078431],
        ...,
        [0.75686275, 0.7254902 , 0.71764706],
        [0.75686275, 0.7254902 , 0.71764706],
        [0.75686275, 0.7254902 , 0.71764706]],

       [[0.17254902, 0.17254902, 0.16470588],
        [0.15686275, 0.15686275, 0.14901961],
        [0.16078431, 0.16078431, 0.15294118],
        ...,
        [0.76470588, 0.73333333, 0.7254902 ],
        [0.76470588, 0.73333333, 0.7254902 ],
        [0.76470588, 0.73333333, 0.7254902 ]],

       ...,

       [[0.24705882, 0.24705882, 0.25490196],
        [0.24705882, 0.24705882, 0.25490196],
        [0.30980392, 0

In [10]:
x = np.asarray(x)
y = np.asarray(y)

In [11]:
x.shape

(11, 256, 256, 3)

In [13]:
# from functools import partial

# defaultcon3d = partial(keras.layers.Conv2D , kernel_size = 3 , activation = 'relu' , padding = "SAME") 
# model = keras.models.Sequential([
#     defaultcon3d(kernel_size = 7 , filters = 64 , input_shape = [256,256,3]),
#     keras.layers.MaxPooling2D(pool_size = 2),
#     defaultcon3d(filters = 64),
#     defaultcon3d(filters = 64),
#     keras.layers.MaxPooling2D(pool_size = 2),
#     defaultcon3d(filters = 128),
#     defaultcon3d(filters = 128),
#     keras.layers.MaxPooling2D(pool_size = 2),
#     keras.layers.Flatten(),
#     keras.layers.Dense(units = 150 , activation = 'relu'),
#     keras.layers.Dropout(0.5),
#     keras.layers.Dense(units = 100 , activation = 'relu'),
#     keras.layers.Dropout(0.5),
#     keras.layers.Dense(units = len(labels) , activation = 'softmax')
# ])

model = keras.models.load_model("modelCNN.h5")

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 256, 256, 64)      9472      
                                                                 
 max_pooling2d (MaxPooling2D  (None, 128, 128, 64)     0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 128, 128, 64)      36928     
                                                                 
 conv2d_2 (Conv2D)           (None, 128, 128, 64)      36928     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 64, 64, 64)       0         
 2D)                                                             
                                                                 
 conv2d_3 (Conv2D)           (None, 64, 64, 128)       7

In [15]:
model.compile(metrics = ["accuracy"] , loss = "sparse_categorical_crossentropy" , optimizer = "adam")

In [16]:
from sklearn.model_selection import train_test_split

In [61]:
xtrain ,  xtest ,ytrain,  ytest = train_test_split(x , y , test_size = 0.2)

In [62]:
type(xtrain)

numpy.ndarray

In [63]:
xtrain.shape

(321, 256, 256, 3)

In [64]:
checkpoint = keras.callbacks.ModelCheckpoint('modelCNN.h5')
earlyStop = keras.callbacks.EarlyStopping(patience = 4 , restore_best_weights = True , monitor = 'accuracy')

In [65]:
history = model.fit(xtrain , ytrain , epochs = 10, callbacks = [checkpoint, earlyStop])

Epoch 1/10
11/11 [==============================] - 95s 8s/step - loss: 0.5577 - accuracy: 0.7352
Epoch 2/10
11/11 [==============================] - 88s 8s/step - loss: 0.1034 - accuracy: 0.9688
Epoch 3/10
11/11 [==============================] - 89s 8s/step - loss: 0.0163 - accuracy: 0.9938
Epoch 4/10
11/11 [==============================] - 89s 8s/step - loss: 0.0039 - accuracy: 1.0000
Epoch 5/10
11/11 [==============================] - 87s 8s/step - loss: 0.0136 - accuracy: 0.9969
Epoch 6/10
11/11 [==============================] - 87s 8s/step - loss: 0.0013 - accuracy: 1.0000
Epoch 7/10
11/11 [==============================] - 87s 8s/step - loss: 8.8936e-05 - accuracy: 1.0000
Epoch 8/10
11/11 [==============================] - 86s 8s/step - loss: 0.0000e+00 - accuracy: 1.0000


In [66]:
history

In [17]:
preds = model.predict(x)

1/1 [==============================] - 1s 970ms/step


In [18]:
type(preds)

numpy.ndarray

In [19]:
ans = []
for pred in preds:
    ans.append(np.argmax(pred))

In [20]:
from sklearn.metrics import confusion_matrix

In [22]:
confusion_matrix(ans , y)

array([[11]], dtype=int64)

In [23]:
list(ans)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [73]:
preds

array([[1.00000000e+00, 2.53752519e-10],
       [1.00000000e+00, 3.71604325e-09],
       [1.00000000e+00, 3.76815662e-11],
       [2.84123717e-14, 1.00000000e+00],
       [1.00000000e+00, 3.03770169e-11],
       [1.00000000e+00, 3.35823799e-11],
       [1.00712543e-13, 1.00000000e+00],
       [1.35119932e-12, 1.00000000e+00],
       [1.00000000e+00, 3.48424567e-10],
       [1.00000000e+00, 3.29315325e-10],
       [1.47223576e-14, 1.00000000e+00],
       [2.46342033e-14, 1.00000000e+00],
       [4.69358656e-13, 1.00000000e+00],
       [1.00000000e+00, 3.48424567e-10],
       [1.87170649e-14, 1.00000000e+00],
       [1.00000000e+00, 3.23018313e-11],
       [1.00000000e+00, 8.14810353e-09],
       [3.70985014e-11, 1.00000000e+00],
       [3.42079143e-11, 1.00000000e+00],
       [1.00000000e+00, 7.42470796e-09],
       [1.00000000e+00, 3.48424567e-10],
       [2.33873420e-14, 1.00000000e+00],
       [1.09269900e-13, 1.00000000e+00],
       [4.11425373e-11, 1.00000000e+00],
       [3.245017